package com.enterprise.business.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * Message payload for Process Request creation.
 * Sent from Business Service to Process Management Service via RabbitMQ.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProcessRequestMessage implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Unique ID for this request (generated by Business Service).
     */
    private UUID requestId;

    /**
     * The process definition key (e.g., "expense-approval-process").
     */
    private String processDefinitionKey;

    /**
     * The user who initiated the request.
     */
    private String initiatorUserId;

    /**
     * Business key for correlation (e.g., Order ID, Invoice Number).
     */
    private String businessKey;

    /**
     * Variables to pass to the process instance.
     */
    private Map<String, Object> variables;

    /**
     * Timestamp when the request was created.
     */
    private Instant createdAt;

    /**
     * Priority (1 = Low, 5 = Normal, 10 = High).
     */
    private int priority;
}
